#!/usr/bin/env bash

THIN_W=2560
THIN_H=267

WIDE_W=600
WIDE_H=1440

WIN_ID=$(wmctrl -l | grep -E "Minecraft\*|MCSR" | awk '{print $1}' | head -n 1)

[ -z "$WIN_ID" ] && exit 0

IS_FULLSCREEN=$(xprop -id $WIN_ID | grep _NET_WM_STATE_FULLSCREEN)

eval "$(xdotool getwindowgeometry --shell "$WIN_ID" 2>/dev/null)"
CURRENT_X=$X
CURRENT_Y=$Y
CURRENT_W=$WIDTH
CURRENT_H=$HEIGHT

get_monitor_geometry() {
    WIN_CENTER_X=$(( CURRENT_X + CURRENT_W / 2 ))
    WIN_CENTER_Y=$(( CURRENT_Y + CURRENT_H / 2 ))

    while read -r GEOM; do
        [ -z "$GEOM" ] && continue

        read -r MON_W MON_H MON_X MON_Y < <(
            echo "$GEOM" | sed -E 's/^([0-9]+)x([0-9]+)([-+][0-9]+)([-+][0-9]+)$/\1 \2 \3 \4/'
        )

        if [ "$WIN_CENTER_X" -ge "$MON_X" ] && [ "$WIN_CENTER_X" -lt $(( MON_X + MON_W )) ] &&
           [ "$WIN_CENTER_Y" -ge "$MON_Y" ] && [ "$WIN_CENTER_Y" -lt $(( MON_Y + MON_H )) ]; then
            echo "$MON_X $MON_Y $MON_W $MON_H"
            return
        fi
    done < <(xrandr --query 2>/dev/null | awk '/ connected/ { for (i = 1; i <= NF; i++) if ($i ~ /^[0-9]+x[0-9]+[-+][0-9]+[-+][0-9]+$/) print $i }')

    SCREEN=$(xdpyinfo | grep dimensions | awk '{print $2}')
    echo "0 0 ${SCREEN%%x*} ${SCREEN#*x}"
}

center_window() {
    WIDTH=$1
    HEIGHT=$2

    read -r MON_X MON_Y MON_W MON_H < <(get_monitor_geometry)

    X=$(( MON_X + (MON_W - WIDTH) / 2 ))
    Y=$(( MON_Y + (MON_H - HEIGHT) / 2 ))

    wmctrl -i -r "$WIN_ID" -b remove,fullscreen
    sleep 0.15
    wmctrl -i -R "$WIN_ID"
    sleep 0.1
    wmctrl -i -r "$WIN_ID" -e "0,$X,$Y,$WIDTH,$HEIGHT"
    sleep 0.1
}
if [ -n "$IS_FULLSCREEN" ]; then
    # Fullscreen -> Thin
    center_window $THIN_W $THIN_H

elif [ "$CURRENT_W" = "$THIN_W" ] && [ "$CURRENT_H" = "$THIN_H" ]; then
    # Thin -> Wide
    center_window $WIDE_W $WIDE_H

elif [ "$CURRENT_W" = "$WIDE_W" ] && [ "$CURRENT_H" = "$WIDE_H" ]; then
    # Wide -> Fullscreen
    wmctrl -i -r "$WIN_ID" -b add,fullscreen

else
    #random
    wmctrl -i -r "$WIN_ID" -b add,fullscreen
fi
